# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/luclabarbe/Desktop/MARC-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/luclabarbe/Desktop/MARC-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luclabarbe/Desktop/MARC-master/CMakeFiles /Users/luclabarbe/Desktop/MARC-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luclabarbe/Desktop/MARC-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MARC_Rover

# Build rule for target.
MARC_Rover: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MARC_Rover
.PHONY : MARC_Rover

# fast build rule for target.
MARC_Rover/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/build
.PHONY : MARC_Rover/fast

loc.o: loc.c.o
.PHONY : loc.o

# target to build an object file
loc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/loc.c.o
.PHONY : loc.c.o

loc.i: loc.c.i
.PHONY : loc.i

# target to preprocess a source file
loc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/loc.c.i
.PHONY : loc.c.i

loc.s: loc.c.s
.PHONY : loc.s

# target to generate assembly for a file
loc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/loc.c.s
.PHONY : loc.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/main.c.s
.PHONY : main.c.s

map.o: map.c.o
.PHONY : map.o

# target to build an object file
map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/map.c.o
.PHONY : map.c.o

map.i: map.c.i
.PHONY : map.i

# target to preprocess a source file
map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/map.c.i
.PHONY : map.c.i

map.s: map.c.s
.PHONY : map.s

# target to generate assembly for a file
map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/map.c.s
.PHONY : map.c.s

moves.o: moves.c.o
.PHONY : moves.o

# target to build an object file
moves.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/moves.c.o
.PHONY : moves.c.o

moves.i: moves.c.i
.PHONY : moves.i

# target to preprocess a source file
moves.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/moves.c.i
.PHONY : moves.c.i

moves.s: moves.c.s
.PHONY : moves.s

# target to generate assembly for a file
moves.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/moves.c.s
.PHONY : moves.c.s

performance.o: performance.c.o
.PHONY : performance.o

# target to build an object file
performance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/performance.c.o
.PHONY : performance.c.o

performance.i: performance.c.i
.PHONY : performance.i

# target to preprocess a source file
performance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/performance.c.i
.PHONY : performance.c.i

performance.s: performance.c.s
.PHONY : performance.s

# target to generate assembly for a file
performance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/performance.c.s
.PHONY : performance.c.s

queue.o: queue.c.o
.PHONY : queue.o

# target to build an object file
queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/queue.c.o
.PHONY : queue.c.o

queue.i: queue.c.i
.PHONY : queue.i

# target to preprocess a source file
queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/queue.c.i
.PHONY : queue.c.i

queue.s: queue.c.s
.PHONY : queue.s

# target to generate assembly for a file
queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/queue.c.s
.PHONY : queue.c.s

simulation.o: simulation.c.o
.PHONY : simulation.o

# target to build an object file
simulation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/simulation.c.o
.PHONY : simulation.c.o

simulation.i: simulation.c.i
.PHONY : simulation.i

# target to preprocess a source file
simulation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/simulation.c.i
.PHONY : simulation.c.i

simulation.s: simulation.c.s
.PHONY : simulation.s

# target to generate assembly for a file
simulation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/simulation.c.s
.PHONY : simulation.c.s

stack.o: stack.c.o
.PHONY : stack.o

# target to build an object file
stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i
.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s
.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/stack.c.s
.PHONY : stack.c.s

tree.o: tree.c.o
.PHONY : tree.o

# target to build an object file
tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/tree.c.o
.PHONY : tree.c.o

tree.i: tree.c.i
.PHONY : tree.i

# target to preprocess a source file
tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/tree.c.i
.PHONY : tree.c.i

tree.s: tree.c.s
.PHONY : tree.s

# target to generate assembly for a file
tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/tree.c.s
.PHONY : tree.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/utils.c.s
.PHONY : utils.c.s

visualization.o: visualization.c.o
.PHONY : visualization.o

# target to build an object file
visualization.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/visualization.c.o
.PHONY : visualization.c.o

visualization.i: visualization.c.i
.PHONY : visualization.i

# target to preprocess a source file
visualization.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/visualization.c.i
.PHONY : visualization.c.i

visualization.s: visualization.c.s
.PHONY : visualization.s

# target to generate assembly for a file
visualization.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MARC_Rover.dir/build.make CMakeFiles/MARC_Rover.dir/visualization.c.s
.PHONY : visualization.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MARC_Rover"
	@echo "... loc.o"
	@echo "... loc.i"
	@echo "... loc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... moves.o"
	@echo "... moves.i"
	@echo "... moves.s"
	@echo "... performance.o"
	@echo "... performance.i"
	@echo "... performance.s"
	@echo "... queue.o"
	@echo "... queue.i"
	@echo "... queue.s"
	@echo "... simulation.o"
	@echo "... simulation.i"
	@echo "... simulation.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... visualization.o"
	@echo "... visualization.i"
	@echo "... visualization.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

